import Layout from "./layout";
import Header from "./header";
import Footer from "./footer";
import Sider from "./sider";
import Content from "./content";
Layout.Header = Header;
Layout.Footer = Footer;
Layout.Sider = Sider;
Layout.Content = Content;
export default Layout;
